### ISSUE TITLE
add webpack code

### ISSUE THREAD

**Issue by timxor** [squanto/brainstream#1]
missing webpack code

**Comment by timxor** [comment]
<img width="1440" alt="screen shot 2019-02-01 at 7 35 43 am" src="https://user-images.githubusercontent.com/2419150/52126141-17059300-25f4-11e9-8d74-d755108ba279.png">

**Comment by squanto** [comment]
Hey @tcsiwula 
I think this line that breaks when opening the app in a normal browser:
```js
const remote = window.require("electron").remote
```
relies on electron apis that are exposed when running the 'page' with electron.

Do you get the same error if you run `yarn start` and open the electron container?

**Comment by timxor** [comment]
roger that @squanto !
